name: AvertoxJobSystem
version: 1.0.0
main: com.avertox.jobsystem.AvertoxJobSystemPlugin
api-version: "1.20"
softdepend: [Vault]
commands:
  jobs:
    description: Job system menu and handlers
    usage: /jobs [sell|upgrade|recipes]
  jobsadmin:
    description: Admin controls for job system
    usage: /jobsadmin [player]
permissions:
  avertoxjobs.admin:
    description: Access to job admin GUI
    default: op
